# Generated by Django 6.0.5 on 2026-05-24 10:10

import apps.forms.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_nominationheader_is_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_number', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('data_ref_value', models.TextField(blank=True, default='')),
                ('document_name', models.CharField(blank=True, default='', max_length=255)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to=apps.forms.models.indicator_file_path)),
                ('uploaded_file_url', models.URLField(blank=True, default='', max_length=500)),
                ('nomination_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='forms.nominationheader')),
            ],
            options={
                'ordering': ['indicator_number'],
                'unique_together': {('nomination_header', 'indicator_number')},
            },
        ),
    ]
