# Generated by Django 6.0.1 on 2026-06-02 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_refreshtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=100)),
                ('head_name', models.CharField(blank=True, max_length=255, null=True)),
                ('head_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('institution_type', models.CharField(blank=True, max_length=100, null=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('score', models.IntegerField(default=0)),
                ('award_category', models.CharField(default='No Award', max_length=50)),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='authentication.college')),
            ],
            options={
                'unique_together': {('form_id', 'college')},
            },
        ),
    ]
